// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.8.2
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(f){"use strict";var
dR="Sys_error",Q=0x80,dm="ENOTEMPTY",b6="compare: functional value",W=" ",dQ="EEXIST",I="0",bZ=1255,aW=1000,b5="mkdir",dC="@[",bY=" : flags Open_text and Open_binary are not compatible",d8="console",b4="fs",dP="\n",b$="e",d7="%u",dB="/static/",dl="Stack_overflow",bX=": Not a directory",b_="ENOENT",dA="%i",d6="%ni",ad=0xff,dO="Undefined_recursive_module",dz="Assert_failure",dy="0x",Y=0x8000,dk=-48,dN=0x800,d5=0x7ff0,dj=" : is a directory",dx=0xdfff,dL="@{",dM="Division_by_zero",an=".",d4="End_of_file",dw=": closedir failed",aG=0x3f,d3="Out_of_memory",dv="Not_found",b9=" : file already exists",cc="Failure",bh=": No such file or directory",aX=128,bi="Unix.Unix_error",d2="^",aF=255,dK=256,cb="ENOTDIR",dJ=100,V="/",bW="index out of bounds",be=252,du="%Li",dt="Invalid_argument",bf=254,aH="+",bV="%d",d1=", characters ",di=": file descriptor already closed",aw="-",bU="EBADF",ac=0xffffff,ds=120,dr=1027,aV=1024,dH=-97,dI="Printexc.handle_uncaught_exception",d0="Pervasives.do_at_exit",dh=12520,b8=" : flags Open_rdonly and Open_wronly are not compatible",dZ=65536,ca=0xf,dq=", ",b3=512,dg="Fatal error: exception %s\n",dX="Match_failure",dY="closedir",dn="%li",dp=1026,dW=-32,df=250,b2="nan",dG=">",e="",b0="Fatal error: exception ",b1="rmdir",dF="([^/]+)",bT="jsError",a="camlinternalFormat.ml",dV="infinity",de=103,bd='"',X=0xffff,b7=127,dU="fd ",dd=0xdc00,dE="Sys_blocked_io",c=248,dc="buffer.ml",dD="_",dT=0xe0,bg="_bigarr02",dS=0xf0;function
bt(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=aV,c-=aV)f+=d.apply(null,a.slice(b,b+Math.min(c,aV)));return f}function
bl(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
af(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?bt(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else if(c.t==2&&d==c.c.length){c.c+=a.t==4?bt(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)bl(c);var
g=a.c,h=c.c;if(a.t==4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aJ(a,b){if(a==0)return e;if(b.repeat)return b.repeat(a);var
d=e,c=0;for(;;){if(a&1)d+=b;a>>=1;if(a==0)return d;b+=b;c++;if(c==9)b.slice(0,1)}}function
bm(a){if(a.t==2)a.c+=aJ(a.l-a.c.length,"\0");else
a.c=bt(a.c,0,a.c.length);a.t=0}function
cy(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>b7)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
ey(a){for(var
k=e,d=e,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<Q){for(var
f=c+1;f<j&&(g=a.charCodeAt(f))<Q;f++);if(f-c>b3){d.substr(0,1);k+=d;d=e;k+=a.slice(c,f)}else
d+=a.slice(c,f);if(f==j)break;c=f}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)==aX){h=i+(g<<6);if(g<dT){b=h-0x3080;if(b<Q)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)==aX){h=i+(h<<6);if(g<dS){b=h-0xe2080;if(b<dN||b>=0xd7ff&&b<0xe000)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)==aX&&g<0xf5){b=i-0x3c82080+(h<<6);if(b<0x10000||b>0x10ffff)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else if(b>X)d+=String.fromCharCode(0xd7c0+(b>>10),dd+(b&0x3FF));else
d+=String.fromCharCode(b);if(d.length>aV){d.substr(0,1);k+=d;d=e}}return k+d}function
ae(a,b,c){this.t=a;this.c=b;this.l=c}ae.prototype.toString=function(){switch(this.t){case
9:return this.c;default:bm(this);case
0:if(cy(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};ae.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return ey(a)};ae.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
ae(this.t,a,this.l)};function
ee(a){return new
ae(0,a,a.length)}function
as(a){return a}function
ap(a){return ee(as(a))}function
aZ(a,b,c,d,e){af(ap(a),b,c,d,e);return 0}function
ih(a){var
b=f.process;if(b&&b.env&&b.env[a]!=undefined)return b.env[a];if(f.jsoo_static_env&&f.jsoo_static_env[a])return f.jsoo_static_env[a]}var
cu=0;(function(){var
c=ih("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]=="b"){cu=1;break}else if(b[a].startsWith("b="))cu=+b[a].slice(2);else
continue}}());var
C=[0];function
hE(a,b){if(!a.js_error||b||a[0]==c)a.js_error=new
f.Error("Js exception containing backtrace");return a}function
h(a,b){return cu?hE(a,b):a}function
h$(a,b){throw h([0,a,b])}function
O(a){return a}function
ct(a,b){h$(a,O(b))}function
j(a){ct(C.Invalid_argument,a)}function
hz(){j(bW)}function
r(a,b,c){c&=ad;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}bl(a)}a.c[b]=c;return 0}function
E(a,b,c){if(b>>>0>=a.l)hz();return r(a,b,c)}function
cf(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
aq(d,c){var
f=d.l>=0?d.l:d.l=d.length,e=c.length,b=f-e;if(b==0)return d.apply(null,c);else if(b<0){var
a=d.apply(null,c.slice(0,f));if(typeof
a!=="function")return a;return aq(a,c.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(e+1);for(var
b=0;b<e;b++)f[b]=c[b];f[e]=a;return d.apply(null,f)};break}case
2:{var
a=function(a,b){var
g=new
Array(e+2);for(var
f=0;f<e;f++)g[f]=c[f];g[e]=a;g[e+1]=b;return d.apply(null,g)};break}default:var
a=function(){var
e=arguments.length==0?1:arguments.length,b=new
Array(c.length+e);for(var
a=0;a<c.length;a++)b[a]=c[a];for(var
a=0;a<arguments.length;a++)b[c.length+a]=arguments[a];return aq(d,b)}}a.l=b;return a}}function
bj(){j(bW)}function
ef(a,b){if(b>>>0>=a.length-1)bj();return a}function
hB(a){if(isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
hC(){return[0]}function
u(a){if(a<0)j("Bytes.create");return new
ae(a?2:9,e,a)}function
hF(a,b,c,d){if(c>0)if(b==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(d==0){a.c=e;a.t=2}else{a.c=aJ(c,String.fromCharCode(d));a.t=c==a.l?0:2}else{if(a.t!=4)bl(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
cs(a){a=as(a);var
e=a.length;if(e>31)j("format_int: format too long");var
b={justify:aH,signstyle:aw,filler:W,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=aw;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=I;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;case"d":case"i":b.signedconv=true;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
ch(a,b){if(a.uppercase)b=b.toUpperCase();var
f=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!=aw))f++;if(a.alternate){if(a.base==8)f+=1;if(a.base==16)f+=2}var
c=e;if(a.justify==aH&&a.filler==W)for(var
d=f;d<a.width;d++)c+=W;if(a.signedconv)if(a.sign<0)c+=aw;else if(a.signstyle!=aw)c+=a.signstyle;if(a.alternate&&a.base==8)c+=I;if(a.alternate&&a.base==16)c+=a.uppercase?"0X":dy;if(a.justify==aH&&a.filler==I)for(var
d=f;d<a.width;d++)c+=I;c+=b;if(a.justify==aw)for(var
d=f;d<a.width;d++)c+=W;return O(c)}function
ci(a,b){function
j(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=parseInt(a.toString().split(aH)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=new
Array(c+1).join(I);if(b>0)a=a+an+new
Array(b+1).join(I);return a}else
return a.toFixed(b)}}var
c,f=cs(a),e=f.prec<0?6:f.prec;if(b<0||b==0&&1/b==-Infinity){f.sign=-1;b=-b}if(isNaN(b)){c=b2;f.filler=W}else if(!isFinite(b)){c="inf";f.filler=W}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)==b$)c=c.slice(0,d-1)+I+c.slice(d-1);break;case"f":c=j(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(b$),h=+c.slice(i+1);if(h<-4||b>=1e21||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)==I)d--;if(c.charAt(d)==an)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)==b$)c=c.slice(0,d-1)+I+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)==I)d--;if(c.charAt(d)==an)d--;c=c.slice(0,d+1)}}break}return ch(f,c)}function
bn(a,b){if(as(a)==bV)return O(e+b);var
c=cs(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
d=b.toString(c.base);if(c.prec>=0){c.filler=W;var
f=c.prec-d.length;if(f>0)d=aJ(f,I)+d}return ch(c,d)}var
h9=0;function
bo(){return h9++}function
ar(a){if(!C.Failure)C.Failure=[c,O(cc),-3];ct(C.Failure,a)}function
cq(a){if(cy(a))return a;return ey(a)}function
a5(){return typeof
f.process!=="undefined"&&typeof
f.process.versions!=="undefined"&&typeof
f.process.versions.node!=="undefined"}function
ij(){function
a(a){if(a.charAt(0)===V)return[e,a.substring(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||e,f=Boolean(c&&c.charAt(1)!==":");if(Boolean(b[2]||f)){var
d=b[1]||e,g=b[2]||e;return[d,a.substring(d.length+g.length)]}return}return a5()&&f.process&&f.process.platform?f.process.platform==="win32"?b:a:a}var
cz=ij();function
ew(a){return a.slice(-1)!==V?a+V:a}if(a5()&&f.process&&f.process.cwd)var
a0=f.process.cwd().replace(/\\/g,V);else
var
a0="/static";a0=ew(a0);function
h2(a){a=cq(a);if(!cz(a))a=a0+a;var
e=cz(a),d=e[1].split(V),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
ie(a){for(var
g=e,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<Q){for(var
f=d+1;f<h&&(b=a.charCodeAt(f))<Q;f++);if(f-d>b3){c.substr(0,1);g+=c;c=e;g+=a.slice(d,f)}else
c+=a.slice(d,f);if(f==h)break;d=f}if(b<dN){c+=String.fromCharCode(0xc0|b>>6);c+=String.fromCharCode(Q|b&aG)}else if(b<0xd800||b>=dx)c+=String.fromCharCode(dT|b>>12,Q|b>>6&aG,Q|b&aG);else if(b>=0xdbff||d+1==h||(i=a.charCodeAt(d+1))<dd||i>dx)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-0x35fdc00;c+=String.fromCharCode(dS|b>>18,Q|b>>12&aG,Q|b>>6&aG,Q|b&aG)}if(c.length>aV){c.substr(0,1);g+=c;c=e}}return g+c}function
_(a){return cy(a)?O(a):O(ie(a))}var
ik=["E2BIG","EACCES","EAGAIN",bU,"EBUSY","ECHILD","EDEADLK","EDOM",dQ,"EFAULT","EFBIG","EINTR","EINVAL","EIO","EISDIR","EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",b_,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",cb,dm,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS","ESPIPE","ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
ai(a,b,c,d){var
f=ik.indexOf(a);if(f<0){if(d==null)d=-9999;f=[0,d]}var
g=[f,_(b||e),_(c||e)];return g}var
et={};function
au(a){return et[a]}function
ah(a,b){throw h([0,a].concat(b))}function
co(a){return a
instanceof
ae}function
cp(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
ce(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
ae(4,a,a.length)}function
g(a){ct(C.Sys_error,a)}function
eu(a){g(a+bh)}function
ex(a){if(a.t!=4)bl(a);return a.c}function
S(a){return a.l}function
d9(){}function
B(a){this.data=a}B.prototype=new
d9();B.prototype.constructor=B;B.prototype.truncate=function(a){var
b=this.data;this.data=u(a|0);af(b,0,this.data,0,a)};B.prototype.length=function(){return S(this.data)};B.prototype.write=function(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=u(a+d),g=this.data;this.data=f;af(g,0,this.data,0,e)}af(ce(b),c,this.data,a,d);return 0};B.prototype.read=function(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d){var
f=u(d|0);af(this.data,a,f,0,d);b.set(ex(f),c)}return d};function
ax(a,b,c){this.file=b;this.name=a;this.flags=c}ax.prototype.err_closed=function(){g(this.name+di)};ax.prototype.length=function(){if(this.file)return this.file.length();this.err_closed()};ax.prototype.write=function(a,b,c,d){if(this.file)return this.file.write(a,b,c,d);this.err_closed()};ax.prototype.read=function(a,b,c,d){if(this.file)return this.file.read(a,b,c,d);this.err_closed()};ax.prototype.close=function(){this.file=undefined};function
w(a,b){this.content={};this.root=a;this.lookupFun=b}w.prototype.nm=function(a){return this.root+a};w.prototype.create_dir_if_needed=function(a){var
d=a.split(V),c=e;for(var
b=0;b<d.length-1;b++){c+=d[b]+V;if(this.content[c])continue;this.content[c]=Symbol("directory")}};w.prototype.slash=function(a){return/\/$/.test(a)?a:a+V};w.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(O(this.root),O(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
B(ap(b[1]))}}};w.prototype.exists=function(a){if(a==e)return 1;var
b=this.slash(a);if(this.content[b])return 1;this.lookup(a);return this.content[a]?1:0};w.prototype.isFile=function(a){return this.exists(a)&&!this.is_dir(a)?1:0};w.prototype.mkdir=function(a,b,c){var
f=c&&au(bi);if(this.exists(a))if(f)ah(f,ai(dQ,b5,this.nm(a)));else
g(a+": File exists");var
d=/^(.*)\/[^/]+/.exec(a);d=d&&d[1]||e;if(!this.exists(d))if(f)ah(f,ai(b_,b5,this.nm(d)));else
g(d+bh);if(!this.is_dir(d))if(f)ah(f,ai(cb,b5,this.nm(d)));else
g(d+bX);this.create_dir_if_needed(this.slash(a))};w.prototype.rmdir=function(a,b){var
c=b&&au(bi),d=a==e?e:this.slash(a),h=new
RegExp(d2+d+dF);if(!this.exists(a))if(c)ah(c,ai(b_,b1,this.nm(a)));else
g(a+bh);if(!this.is_dir(a))if(c)ah(c,ai(cb,b1,this.nm(a)));else
g(a+bX);for(var
f
in
this.content)if(f.match(h))if(c)ah(c,ai(dm,b1,this.nm(a)));else
g(this.nm(a)+": Directory not empty");delete
this.content[d]};w.prototype.readdir=function(a){var
h=a==e?e:this.slash(a);if(!this.exists(a))g(a+bh);if(!this.is_dir(a))g(a+bX);var
i=new
RegExp(d2+h+dF),d={},c=[];for(var
f
in
this.content){var
b=f.match(i);if(b&&!d[b[1]]){d[b[1]]=true;c.push(b[1])}}return c};w.prototype.opendir=function(a,b){var
c=b&&au(bi),d=this.readdir(a),e=false,f=0;return{readSync:function(){if(e)if(c)ah(c,ai(bU,dY,this.nm(a)));else
g(a+dw);if(f==d.length)return null;var
b=d[f];f++;return{name:b}},closeSync:function(){if(e)if(c)ah(c,ai(bU,dY,this.nm(a)));else
g(a+dw);e=true;d=[]}}};w.prototype.is_dir=function(a){if(a==e)return true;var
b=this.slash(a);return this.content[b]?1:0};w.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};w.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)g(this.nm(a)+b8);if(b.text&&b.binary)g(this.nm(a)+bY);this.lookup(a);if(this.content[a]){if(this.is_dir(a))g(this.nm(a)+dj);if(b.create&&b.excl)g(this.nm(a)+b9);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
B(u(0));c=this.content[a]}else
eu(this.nm(a));return new
ax(this.nm(a),c,b)};w.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)g(this.nm(a)+b8);if(b.text&&b.binary)g(this.nm(a)+bY);this.lookup(a);if(this.content[a]){if(this.is_dir(a))g(this.nm(a)+dj);if(b.create&&b.excl)g(this.nm(a)+b9);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
B(u(0));c=this.content[a]}else
eu(this.nm(a));return new
ax(this.nm(a),c,b)};w.prototype.register=function(a,b){var
c;if(this.content[a])g(this.nm(a)+b9);if(co(b))c=new
B(b);if(cp(b))c=new
B(ap(b));else if(b
instanceof
Array)c=new
B(ce(b));else if(typeof
b==="string")c=new
B(ee(b));else if(b.toString){var
d=ap(_(b.toString()));c=new
B(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
g(this.nm(a)+" : registering file with invalid content type")};w.prototype.constructor=w;function
o(a){return a.length}function
aK(a,b){return a.charCodeAt(b)}function
ip(a){var
d=o(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=aK(a,b);return c}function
R(a,b){this.fs=require(b4);this.fd=a;this.flags=b}R.prototype=new
d9();R.prototype.constructor=R;R.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(f){g(f.toString())}};R.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(f){g(f.toString())}};R.prototype.write=function(a,b,c,d){try{if(this.flags.isCharacterDevice)this.fs.writeSync(this.fd,b,c,d);else
this.fs.writeSync(this.fd,b,c,d,a)}catch(f){g(f.toString())}return 0};R.prototype.read=function(a,b,c,d){try{if(this.flags.isCharacterDevice)var
e=this.fs.readSync(this.fd,b,c,d);else
var
e=this.fs.readSync(this.fd,b,c,d,a);return e}catch(f){g(f.toString())}};R.prototype.close=function(){try{this.fs.closeSync(this.fd);return 0}catch(f){g(f.toString())}};function
b(a){this.fs=require(b4);this.root=a}b.prototype.nm=function(a){return this.root+a};b.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}};b.prototype.isFile=function(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){g(f.toString())}};b.prototype.mkdir=function(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){g(f.toString())}};b.prototype.unlink=function(a,b){try{var
c=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return c}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.open=function(a,b,c){var
d=require("constants"),e=0;for(var
h
in
b)switch(h){case"rdonly":e|=d.O_RDONLY;break;case"wronly":e|=d.O_WRONLY;break;case"append":e|=d.O_WRONLY|d.O_APPEND;break;case"create":e|=d.O_CREAT;break;case"truncate":e|=d.O_TRUNC;break;case"excl":e|=d.O_EXCL;break;case"binary":e|=d.O_BINARY;break;case"text":e|=d.O_TEXT;break;case"nonblock":e|=d.O_NONBLOCK;break}try{var
f=this.fs.openSync(this.nm(a),e),g=this.fs.lstatSync(this.nm(a)).isCharacterDevice();b.isCharacterDevice=g;return new
R(f,b)}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rename=function(a,b,c){try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.stat=function(a,b){try{var
c=this.fs.statSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.lstat=function(a,b){try{var
c=this.fs.lstatSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.symlink=function(a,b,c,d){try{this.fs.symlinkSync(this.nm(b),this.nm(c),a?"dir":"file");return 0}catch(f){this.raise_nodejs_error(f,d)}};b.prototype.readlink=function(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return _(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.opendir=function(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.raise_nodejs_error=function(a,b){var
c=au(bi);if(b&&c){var
d=ai(a.code,a.syscall,a.path,a.errno);ah(c,d)}else
g(a.toString())};b.prototype.stats_from_js=function(a){var
b;if(a.isFile())b=0;else if(a.isDirectory())b=1;else if(a.isCharacterDevice())b=2;else if(a.isBlockDevice())b=3;else if(a.isSymbolicLink())b=4;else if(a.isFIFO())b=5;else if(a.isSocket())b=6;return[0,a.dev,a.ino,b,a.mode,a.nlink,a.uid,a.gid,a.rdev,a.size,a.atimeMs,a.mtimeMs,a.ctimeMs]};b.prototype.constructor=b;function
em(a){var
b=cz(a);if(!b)return;return b[0]+V}var
bs=em(a0)||ar("unable to compute caml_root"),aL=[];if(a5())aL.push({path:bs,device:new
b(bs)});else
aL.push({path:bs,device:new
w(bs)});aL.push({path:dB,device:new
w(dB)});function
ez(a){var
i=h2(a),a=i.join(V),h=ew(a),d;for(var
f=0;f<aL.length;f++){var
c=aL[f];if(h.search(c.path)==0&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}if(!d&&a5()){var
e=em(a);if(e&&e.match(/^[a-zA-Z]:\/$/)){var
c={path:e,device:new
b(e)};aL.push(c);d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}}if(d)return d;g("no device found for "+h)}function
hD(a,b){var
c=ez(a);if(!c.device.register)ar("cannot register file");c.device.register(c.rest,b);return 0}function
cx(a,b){var
a=O(a),b=O(b);return hD(a,b)}function
hH(){var
b=f.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)cx(b[a].name,b[a].content);f.jsoo_create_file=cx;f.caml_fs_tmp=[];return 0}function
el(){return[0]}function
hJ(a,b,c){if(!isFinite(a)){if(isNaN(a))return _(b2);return _(a>0?dV:"-infinity")}var
k=a==0&&1/a==-Infinity?1:a>=0?0:1;if(k)a=-a;var
f=0;if(a==0);else if(a<1)while(a<1&&f>-1022){a*=2;f--}else
while(a>=2){a/=2;f++}var
l=f<0?e:aH,g=e;if(k)g=aw;else
switch(c){case
43:g=aH;break;case
32:g=W;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(an);if(j<0)d+=an+aJ(b,I);else{var
h=j+1+b;if(d.length<h)d+=aJ(h-d.length,I);else
d=d.substr(0,h)}}return _(g+dy+d+"p"+l+f.toString(10))}function
hQ(a){return+a.isZero()}var
eo=Math.pow(2,-24);function
h_(a){throw a}function
ev(){h_(C.Division_by_zero)}function
d(a,b,c){this.lo=a&ac;this.mi=b&ac;this.hi=c&X}d.prototype.caml_custom="_j";d.prototype.copy=function(){return new
d(this.lo,this.mi,this.hi)};d.prototype.ucompare=function(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.compare=function(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.neg=function(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
d(a,b,c)};d.prototype.add=function(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),e=this.hi+a.hi+(c>>24);return new
d(b,c,e)};d.prototype.sub=function(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),e=this.hi-a.hi+(c>>24);return new
d(b,c,e)};d.prototype.mul=function(a){var
b=this.lo*a.lo,c=(b*eo|0)+this.mi*a.lo+this.lo*a.mi,e=(c*eo|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
d(b,c,e)};d.prototype.isZero=function(){return(this.lo|this.mi|this.hi)==0};d.prototype.isNeg=function(){return this.hi<<16<0};d.prototype.and=function(a){return new
d(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)};d.prototype.or=function(a){return new
d(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)};d.prototype.xor=function(a){return new
d(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)};d.prototype.shift_left=function(a){a=a&63;if(a==0)return this;if(a<24)return new
d(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
d(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
d(0,0,this.lo<<a-48)};d.prototype.shift_right_unsigned=function(a){a=a&63;if(a==0)return this;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
d(this.hi>>a-48,0,0)};d.prototype.shift_right=function(a){a=a&63;if(a==0)return this;var
c=this.hi<<16>>16;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&X);return new
d(this.hi<<16>>a-32,b,b)};d.prototype.lsl1=function(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&ac;this.lo=this.lo<<1&ac};d.prototype.lsr1=function(){this.lo=(this.lo>>>1|this.mi<<23)&ac;this.mi=(this.mi>>>1|this.hi<<23)&ac;this.hi=this.hi>>>1};d.prototype.udivmod=function(a){var
e=0,c=this.copy(),b=a.copy(),f=new
d(0,0,0);while(c.ucompare(b)>0){e++;b.lsl1()}while(e>=0){e--;f.lsl1();if(c.ucompare(b)>=0){f.lo++;c=c.sub(b)}b.lsr1()}return{quotient:f,modulus:c}};d.prototype.div=function(a){var
b=this;if(a.isZero())ev();var
d=b.hi^a.hi;if(b.hi&Y)b=b.neg();if(a.hi&Y)a=a.neg();var
c=b.udivmod(a).quotient;if(d&Y)c=c.neg();return c};d.prototype.mod=function(a){var
b=this;if(a.isZero())ev();var
d=b.hi;if(b.hi&Y)b=b.neg();if(a.hi&Y)a=a.neg();var
c=b.udivmod(a).modulus;if(d&Y)c=c.neg();return c};d.prototype.toInt=function(){return this.lo|this.mi<<24};d.prototype.toFloat=function(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo};d.prototype.toArray=function(){return[this.hi>>8,this.hi&ad,this.mi>>16,this.mi>>8&ad,this.mi&ad,this.lo>>16,this.lo>>8&ad,this.lo&ad]};d.prototype.lo32=function(){return this.lo|(this.mi&ad)<<24};d.prototype.hi32=function(){return this.mi>>>8&X|this.hi<<16};function
hT(a){return new
d(a&ac,a>>24&ac,a>>31&X)}function
hU(a){return a.toInt()}function
hP(a){return+a.isNeg()}function
hS(a){return a.neg()}function
hN(a,b){var
c=cs(a);if(c.signedconv&&hP(b)){c.sign=-1;b=hS(b)}var
d=e,i=hT(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(hU(g.modulus))+d}while(!hQ(b));if(c.prec>=0){c.filler=W;var
f=c.prec-d.length;if(f>0)d=aJ(f,I)+d}return ch(c,d)}var
bk=aq;function
hZ(a){return a.l>=0?a.l:a.l=a.length}function
h0(a){return function(){var
d=hZ(a),c=new
Array(d);for(var
b=0;b<d;b++)c[b]=arguments[b];return bk(a,c)}}function
hX(a){return 0}var
ii=Math.log2&&Math.log2(1.1235582092889474E+307)==1020;function
ig(a){if(ii)return Math.floor(Math.log2(a));var
b=0;if(a==0)return-Infinity;if(a>=1)while(a>=2){a/=2;b++}else
while(a<1){a*=2;b--}return b}function
cj(a){var
b=new
Float32Array(1);b[0]=a;var
c=new
Int32Array(b.buffer);return c[0]|0}function
bq(a,b,c){return new
d(a,b,c)}function
bp(a){if(!isFinite(a)){if(isNaN(a))return bq(1,0,d5);return a>0?bq(0,0,d5):bq(0,0,0xfff0)}var
f=a==0&&1/a==-Infinity?Y:a>=0?0:Y;if(f)a=-a;var
b=ig(a)+1023;if(b<=0){b=0;a/=Math.pow(2,-dp)}else{a/=Math.pow(2,b-dr);if(a<16){a*=2;b-=1}if(b==0)a/=2}var
d=Math.pow(2,24),c=a|0;a=(a-c)*d;var
e=a|0;a=(a-e)*d;var
g=a|0;c=c&ca|f|b<<4;return bq(g,e,c)}function
a2(a){return a.toArray()}function
ed(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom==bg)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<X)a.write(16,b.dims[d]);else{a.write(16,X);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=a2(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=a2(bp(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
0:for(var
d=0;d<b.data.length;d++){var
f=cj(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,cj(e[1]));a.write(32,cj(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=a2(bp(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=a2(bp(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}function
eb(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
hw(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break}if(!c)j("Bigarray.create: unsupported kind");var
d=new
c(b*eb(a));return d}function
ck(a){var
b=new
Int32Array(1);b[0]=a;var
c=new
Float32Array(b.buffer);return c[0]}function
a1(a){return new
d(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
cl(a){var
f=a.lo,g=a.mi,c=a.hi,d=(c&0x7fff)>>4;if(d==2047)return(f|g|c&ca)==0?c&Y?-Infinity:Infinity:NaN;var
e=Math.pow(2,-24),b=(f*e+g)*e+(c&ca);if(d>0){b+=16;b*=Math.pow(2,d-dr)}else
b*=Math.pow(2,-dp);if(c&Y)b=-b;return b}function
cd(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)j("Bigarray.create: negative dimension");c=c*a[b]}return c}function
hM(a,b){return new
d(a&ac,a>>>24&ad|(b&X)<<8,b>>>16&X)}function
cm(a){return a.hi32()}function
cn(a){return a.lo32()}var
hx=bg;function
ao(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}ao.prototype.caml_custom=hx;ao.prototype.offset=function(a){var
c=0;if(typeof
a==="number")a=[a];if(!(a
instanceof
Array))j("bigarray.js: invalid offset");if(this.dims.length!=a.length)j("Bigarray.get/set: bad number of dimensions");if(this.layout==0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])bj();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])bj();c=c*this.dims[b]+(a[b]-1)}return c};ao.prototype.get=function(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return hM(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[bf,e,c];default:return this.data[a]}};ao.prototype.set=function(a,b){switch(this.kind){case
7:this.data[a*2+0]=cn(b);this.data[a*2+1]=cm(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;default:this.data[a]=b;break}return 0};ao.prototype.fill=function(a){switch(this.kind){case
7:var
c=cn(a),e=cm(a);if(c==e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2==0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d==f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2==0?d:f;break;default:this.data.fill(a);break}};ao.prototype.compare=function(a,b){if(this.layout!=a.layout||this.kind!=a.kind){var
f=this.kind|this.layout<<8,g=a.kind|a.layout<<8;return g-f}if(this.dims.length!=a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!=a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!=e){if(!b)return NaN;if(d==d)return 1;if(e==e)return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0};function
aI(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}aI.prototype=new
ao();aI.prototype.offset=function(a){if(typeof
a!=="number")if(a
instanceof
Array&&a.length==1)a=a[0];else
j("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])bj();return a};aI.prototype.get=function(a){return this.data[a]};aI.prototype.set=function(a,b){this.data[a]=b;return 0};aI.prototype.fill=function(a){this.data.fill(a);return 0};function
d$(a,b,c,d){var
e=eb(a);if(cd(c)*e!=d.length)j("length doesn't match dims");if(b==0&&c.length==1&&e==1)return new
aI(a,b,c,d);return new
ao(a,b,c,d)}function
ea(a,b,c){var
k=a.read32s();if(k<0||k>16)ar("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&ad,q=r>>8&1,j=[];if(c==bg)for(var
d=0;d<k;d++){var
p=a.read16u();if(p==X){var
u=a.read32u(),v=a.read32u();if(u!=0)ar("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=cd(j),h=hw(l,f),i=d$(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)ar("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=a1(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=cl(a1(g));i.set(d,m)}break;case
0:for(var
d=0;d<f;d++){var
m=ck(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=ck(a.read32s()),n=ck(a.read32s());i.set(d,[bf,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=cl(a1(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=cl(a1(g));i.set(d,[bf,o,n])}break}b[0]=(4+k)*4;return d$(l,q,j,h)}function
d_(a,b,c){return a.compare(b,c)}function
es(a,b){return Math.imul(a,b)}function
ag(a,b){b=es(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=es(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
hI(a,b){a=ag(a,cn(b));a=ag(a,cm(b));return a}function
en(a,b){return hI(a,bp(b))}function
ec(a){var
c=cd(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>dK)c=dK;var
e=0,b=0;for(b=0;b+4<=a.data.length;b+=4){e=a.data[b+0]|a.data[b+1]<<8|a.data[b+2]<<16|a.data[b+3]<<24;d=ag(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=ag(d,e)}break;case
4:case
5:if(c>aX)c=aX;var
e=0,b=0;for(b=0;b+2<=a.data.length;b+=2){e=a.data[b+0]|a.data[b+1]<<16;d=ag(d,e)}if((c&1)!=0)d=ag(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=ag(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=ag(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=ag(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=en(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=en(d,a.data[b]);break}return d}function
hK(a,b){b[0]=4;return a.read32s()}function
h8(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:ar("input_value: native integer value too large");default:ar("input_value: ill-formed native integer")}}function
hV(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return a1(d)}function
hR(a,b,c){var
e=a2(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
hL(a,b,c){return a.compare(b)}function
hO(a){return a.lo32()^a.hi32()}var
ej={"_j":{deserialize:hV,serialize:hR,fixed_length:8,compare:hL,hash:hO},"_i":{deserialize:hK,fixed_length:4},"_n":{deserialize:h8,fixed_length:4},"_bigarray":{deserialize:function(a,b){return ea(a,b,"_bigarray")},serialize:ed,compare:d_,hash:ec},"_bigarr02":{deserialize:function(a,b){return ea(a,b,bg)},serialize:ed,compare:d_,hash:ec}};function
cg(a){return ej[a.caml_custom]&&ej[a.caml_custom].compare}function
eh(a,b,c,d){var
f=cg(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&e!=e)return c;if(+e!=+e)return+e;if((e|0)!=0)return e|0}return c}function
ei(a){if(typeof
a==="number")return aW;else if(co(a))return be;else if(cp(a))return 1252;else if(a
instanceof
Array&&a[0]===a[0]>>>0&&a[0]<=aF){var
b=a[0]|0;return b==bf?0:b}else if(a
instanceof
String)return dh;else if(typeof
a=="string")return dh;else if(a
instanceof
Number)return aW;else if(a&&a.caml_custom)return bZ;else if(a&&a.compare)return 1256;else if(typeof
a=="function")return 1247;else if(typeof
a=="symbol")return 1251;return 1001}function
hW(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
im(a,b){return a<b?-1:a>b?1:0}function
hA(a,b){a.t&6&&bm(a);b.t&6&&bm(b);return a.c<b.c?-1:a.c>b.c?1:0}function
eg(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=ei(a);if(e==df){a=a[1];continue}var
g=ei(b);if(g==df){b=b[1];continue}if(e!==g){if(e==aW){if(g==bZ)return eh(a,b,-1,c);return-1}if(g==aW){if(e==bZ)return eh(b,a,1,c);return 1}return e<g?-1:1}switch(e){case
247:j(b6);break;case
248:var
d=hW(a[2],b[2]);if(d!=0)return d|0;break;case
249:j(b6);break;case
250:j("equal: got Forward_tag, should not happen");break;case
251:j("equal: abstract value");break;case
252:if(a!==b){var
d=hA(a,b);if(d!=0)return d|0}break;case
253:j("equal: got Double_tag, should not happen");break;case
254:j("equal: got Double_array_tag, should not happen");break;case
255:j("equal: got Custom_tag, should not happen");break;case
1247:j(b6);break;case
1255:var
i=cg(a);if(i!=cg(b))return a.caml_custom<b.caml_custom?-1:1;if(!i)j("compare: abstract value");var
d=i(a,b,c);if(d!=d)return c?-1:d;if(d!==(d|0))return-1;if(d!=0)return d|0;break;case
1256:var
d=a.compare(b,c);if(d!=d)return c?-1:d;if(d!==(d|0))return-1;if(d!=0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!c)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!c)return NaN;if(a==a)return 1;if(b==b)return-1}break;case
1251:if(a!==b){if(!c)return NaN;return 1}break;case
1252:var
a=as(a),b=as(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
246:case
254:default:if(hX(e)){j("compare: continuation value");break}if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length==0)return 0;var
h=f.pop();b=f.pop();a=f.pop();if(h+1<a.length)f.push(a,b,h+1);a=a[h];b=b[h]}}function
h1(a,b){return+(eg(a,b,false)<0)}function
h3(){return 0}var
at=new
Array();function
ep(a){return at[a]}function
Z(a){var
b=ep(a);if(!b.opened)g("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr==0)return 0;if(b.output)b.output(bt(b.buffer,0,b.buffer_curr));else
b.file.write(b.offset,b.buffer,0,b.buffer_curr);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}function
id(a,b){if(b.name)try{var
d=require(b4),c=d.openSync(b.name,"rs");return new
R(c,b)}catch(f){}return new
R(a,b)}var
bu=new
Array(3);function
aY(a,b){B.call(this,u(0));this.log=function(a){return 0};if(a==1&&typeof
console.log=="function")this.log=console.log;else if(a==2&&typeof
console.error=="function")this.log=console.error;else if(typeof
console.log=="function")this.log=console.log;this.flags=b}aY.prototype.length=function(){return 0};aY.prototype.write=function(a,b,c,d){if(this.log){if(d>0&&c>=0&&c+d<=b.length&&b[c+d-1]==10)d--;var
e=u(d);af(ce(b),c,e,0,d);this.log(e.toUtf16());return 0}g(this.fd+di)};aY.prototype.read=function(a,b,c,d){g(this.fd+": file descriptor is write only")};aY.prototype.close=function(){this.log=undefined};function
bv(a,b){if(b==undefined)b=bu.length;bu[b]=a;return b|0}function
io(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}if(d.rdonly&&d.wronly)g(as(a)+b8);if(d.text&&d.binary)g(as(a)+bY);var
e=ez(a),f=e.device.open(e.rest,d);return bv(f,undefined)}(function(){function
a(a,b){return a5()?id(a,b):new
aY(a,b)}bv(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);bv(a(1,{buffered:2,wronly:1,isCharacterDevice:true}),1);bv(a(2,{buffered:2,wronly:1,isCharacterDevice:true}),2)}());function
h4(a){var
b=bu[a];if(b.flags.wronly)g(dU+a+" is writeonly");var
d=null,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(dZ),refill:d};at[c.fd]=c;return c.fd}function
eq(a){var
b=bu[a];if(b.flags.rdonly)g(dU+a+" is readonly");var
d=b.flags.buffered!==undefined?b.flags.buffered:1,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(dZ),buffered:d};at[c.fd]=c;return c.fd}function
h5(){var
b=0;for(var
a=0;a<at.length;a++)if(at[a]&&at[a].opened&&at[a].out)b=[0,at[a].fd,b];return b}function
h7(a,b,c,d){var
e=ep(a);if(!e.opened)g("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
h=new
Uint8Array(e.buffer_curr+b.length);h.set(e.buffer);e.buffer=h}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;Z(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)Z(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)Z(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;Z(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
h6(a,b,c,d){var
b=ex(b);return h7(a,b,c,d)}function
cr(a,b,c,d){return h6(a,ap(b),c,d)}function
er(a,b){var
c=O(String.fromCharCode(b));cr(a,c,0,1);return 0}function
a3(a,b){return+(eg(a,b,false)!=0)}function
br(a){if(a
instanceof
Array&&a[0]==a[0]>>>0)return a[0];else if(co(a))return be;else if(cp(a))return be;else if(a
instanceof
Function||typeof
a=="function")return 247;else if(a&&a.caml_custom)return aF;else
return aW}function
hy(a){var
c={};if(a)for(var
b=1;b<a.length;b++)c[cq(a[b][1])]=a[b][2];return c}function
N(a,b,c){if(c){var
d=c;if(f.toplevelReloc)a=bk(f.toplevelReloc,[d]);else if(C.symbols){if(!C.symidx)C.symidx=hy(C.symbols);var
e=C.symidx[d];if(e>=0)a=e;else
ar("caml_register_global: cannot locate "+d)}}C[a+1]=b;if(c)C[c]=b}function
cv(a,b){et[as(a)]=b;return 0}function
ib(){j(bW)}function
J(a,b){if(b>>>0>=o(a))ib();return aK(a,b)}function
F(a){a.t&6&&bm(a);return O(a.c)}function
ic(){return 0x7FFFFFFF/4|0}function
cw(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
x(a,b){return{joo_tramp:a,joo_args:b}}function
a4(a){{if(a
instanceof
Array)return a;var
b;if(f.RangeError&&a
instanceof
f.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=C.Stack_overflow;else if(f.InternalError&&a
instanceof
f.InternalError&&a.message&&a.message.match(/too much recursion/i))b=C.Stack_overflow;else if(a
instanceof
f.Error&&au(bT))b=[0,au(bT),a];else
b=[0,C.Failure,_(String(a))];if(a
instanceof
f.Error)b.js_error=a;return b}}function
hY(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
hG(a){var
b=e;if(a[0]==0){b+=a[1][1];if(a.length==3&&a[2][0]==0&&hY(a[1]))var
g=a[2],h=1;else
var
h=2,g=a;b+="(";for(var
f=h;f<g.length;f++){if(f>h)b+=dq;var
d=g[f];if(typeof
d=="number")b+=d.toString();else if(d
instanceof
ae)b+=bd+d.toString()+bd;else if(typeof
d=="string")b+=bd+d.toString()+bd;else
b+=dD}b+=")"}else if(a[0]==c)b+=a[1];return b}function
ek(a){if(a
instanceof
Array&&(a[0]==0||a[0]==c)){var
d=au(dI);if(d)bk(d,[a,false]);else{var
e=hG(a),b=au(d0);if(b)bk(b,[0]);console.error(b0+e);if(a.js_error)throw a.js_error}}else
throw a}function
ia(){var
c=f.process;if(c&&c.on)c.on("uncaughtException",function(a,b){ek(a);c.exit(2)});else if(f.addEventListener)f.addEventListener("error",function(a){if(a.error)ek(a.error)})}ia();function
n(a,b){return(a.l>=0?a.l:a.l=a.length)==1?a(b):aq(a,[b])}function
M(a,b,c){return(a.l>=0?a.l:a.l=a.length)==2?a(b,c):aq(a,[b,c])}function
bc(a,b,c,d){return(a.l>=0?a.l:a.l=a.length)==3?a(b,c,d):aq(a,[b,c,d])}function
bS(a,b,c,d,e,f){return(a.l>=0?a.l:a.l=a.length)==5?a(b,c,d,e,f):aq(a,[b,c,d,e,f])}function
hv(a,b,c,d,e,f,g,h){return(a.l>=0?a.l:a.l=a.length)==7?a(b,c,d,e,f,g,h):aq(a,[b,c,d,e,f,g,h])}var
il=undefined;cx("/static/files/tile_set.txt","extra_character_a.png\nextra_character_b.png\nextra_character_c.png\nextra_character_d.png\nextra_character_e.png\n");hH();var
bz=[c,d3,-1],cE=[c,dR,-2],cB=[c,cc,-3],cA=[c,dt,-4],aM=[c,dv,-7],cC=[c,dX,-8],cD=[c,dl,-9],q=[c,dz,-11],cF=[c,dO,-12],hu=[4,0,0,0,[12,45,[4,0,0,0,0]]],bG=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,d1,[4,0,0,0,[12,45,[4,0,0,0,[11,": ",[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'],c0=[0,e,0,e];N(11,cF,dO);N(10,q,dz);N(9,[c,dE,-10],dE);N(8,cD,dl);N(7,cC,dX);N(6,aM,dv);N(5,[c,dM,-6],dM);N(4,[c,d4,-5],d4);N(3,cA,dt);N(2,cB,cc);N(1,cE,dR);N(0,bz,d3);function
p(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,p(a[1])];case
1:return[1,p(a[1])];case
2:return[2,p(a[1])];case
3:return[3,p(a[1])];case
4:return[4,p(a[1])];case
5:return[5,p(a[1])];case
6:return[6,p(a[1])];case
7:return[7,p(a[1])];case
8:var
c=a[1];return[8,c,p(a[2])];case
9:var
b=a[1];return[9,b,b,p(a[3])];case
10:return[10,p(a[1])];case
11:return[11,p(a[1])];case
12:return[12,p(a[1])];case
13:return[13,p(a[1])];default:return[14,p(a[1])]}}function
A(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,A(a[1],b)];case
1:return[1,A(a[1],b)];case
2:return[2,A(a[1],b)];case
3:return[3,A(a[1],b)];case
4:return[4,A(a[1],b)];case
5:return[5,A(a[1],b)];case
6:return[6,A(a[1],b)];case
7:return[7,A(a[1],b)];case
8:var
c=a[1];return[8,c,A(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,A(a[3],b)];case
10:return[10,A(a[1],b)];case
11:return[11,A(a[1],b)];case
12:return[12,A(a[1],b)];case
13:return[13,A(a[1],b)];default:return[14,A(a[1],b)]}}function
m(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,m(a[1],b)];case
1:return[1,m(a[1],b)];case
2:var
c=a[1];return[2,c,m(a[2],b)];case
3:var
d=a[1];return[3,d,m(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,m(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,m(a[4],b)];case
6:var
k=a[3],l=a[2],n=a[1];return[6,n,l,k,m(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,m(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,m(a[4],b)];case
9:var
u=a[1];return[9,u,m(a[2],b)];case
10:return[10,m(a[1],b)];case
11:var
v=a[1];return[11,v,m(a[2],b)];case
12:var
w=a[1];return[12,w,m(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,m(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,m(a[3],b)];case
15:return[15,m(a[1],b)];case
16:return[16,m(a[1],b)];case
17:var
B=a[1];return[17,B,m(a[2],b)];case
18:var
C=a[1];return[18,C,m(a[2],b)];case
19:return[19,m(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,m(a[3],b)];case
21:var
F=a[1];return[21,F,m(a[2],b)];case
22:return[22,m(a[1],b)];case
23:var
G=a[1];return[23,G,m(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,m(a[3],b)]}}function
bx(a,b,c){return a[1]===b?(a[1]=c,1):0}function
by(a){throw h([0,cB,a],1)}function
aj(a){throw h([0,cA,a],1)}function
a6(a){return 0<=a?a:-a|0}var
eC="true",eD="false";h4(0);var
eE=eq(1),L=eq(2);function
aN(a,b){cr(a,b,0,o(b));return}function
cG(a){aN(L,a);er(L,10);return Z(L)}var
bw=[0,function(a){var
b=h5(0);for(;;){if(!b)return 0;var
d=b[2],e=b[1];try{Z(e)}catch(f){var
c=a4(f);if(c[1]!==cE)throw h(c,0)}b=d}}];function
bA(a){return n(bw[1],0)}cv(d0,bA);var
aO=(4*ic(0)|0)-1|0,eN="String.sub / Bytes.sub",eO="Bytes.blit",eP="String.blit / Bytes.blit_string";function
av(a,b){var
c=u(a);hF(c,0,a,b);return c}function
cH(a,b,c){if(0<=b&&0<=c&&(S(a)-c|0)>=b){var
d=u(c);af(a,b,d,0,c);return d}return aj(eN)}function
cI(a,b,c){return F(cH(a,b,c))}function
cJ(a,b,c,d,e){if(0<=e&&0<=b&&(S(a)-e|0)>=b&&0<=d&&(S(c)-e|0)>=d){af(a,b,c,d,e);return}return aj(eO)}function
$(a,b,c,d,e){if(0<=e&&0<=b&&(o(a)-e|0)>=b&&0<=d&&(S(c)-e|0)>=d){aZ(a,b,c,d,e);return}return aj(eP)}function
cK(a,b){return F(av(a,b))}function
cL(a,b,c){return F(cH(ap(a),b,c))}function
aP(a){return[0,0,0]}function
aQ(a){a[1]=0;a[2]=0;return}function
ay(a,b){b[1]=[0,a,b[1]];b[2]=b[2]+1|0;return}function
az(a){var
b=a[1];if(!b)return 0;var
c=b[1];a[1]=b[2];a[2]=a[2]-1|0;return[0,c]}function
aA(a){var
b=a[1];return b?[0,b[1]]:0}function
bB(a){a[1]=0;a[2]=0;a[3]=0;return}function
cM(a,b){var
c=[0,a,0],d=b[3];if(d){b[1]=b[1]+1|0;d[2]=c;b[3]=c;return}b[1]=1;b[2]=c;b[3]=c;return}var
eR=[0,dc,94,2],eS=[0,dc,93,2],eT="Buffer.add: cannot grow buffer";function
cN(a){var
b=1<=a?a:1,c=aO<b?aO:b,d=u(c);return[0,d,0,c,d]}function
bC(a,b){var
d=a[2],c=[0,a[3]];for(;;){if(c[1]>=(d+b|0))break;c[1]=2*c[1]|0}if(aO<c[1])if((d+b|0)<=aO)c[1]=aO;else
by(eT);var
e=u(c[1]);cJ(a[1],0,e,0,a[2]);a[1]=e;a[3]=c[1];if((a[2]+b|0)>a[3])throw h([0,q,eS],1);if((d+b|0)<=a[3])return;throw h([0,q,eR],1)}function
aR(a,b){var
c=o(b),d=a[2]+c|0;if(a[3]<d)bC(a,c);aZ(b,0,a[1],a[2],c);a[2]=d;return}var
eV="@]",eW="@}",eX="@?",eY="@\n",eZ="@.",e0="@@",e1="@%",e2="%c",e3="%s",e4=dA,e5=dn,e6=d6,e7=du,e8="%f",e9="%B",e_="%{",e$="%}",fa="%(",fb="%)",fc="%a",fd="%t",fe="%?",ff="%r",fg="%_r",fh=[0,a,850,23],fi=[0,a,837,26],fj=[0,a,847,28],fk=[0,a,815,21],fl=[0,a,819,21],fm=[0,a,823,19],fn=[0,a,827,22],fo=[0,a,832,30],fp=[0,a,851,23],fq=[0,a,836,26],fr=[0,a,846,28],fs=[0,a,814,21],ft=[0,a,818,21],fu=[0,a,822,19],fv=[0,a,826,22],fw=[0,a,831,30];function
bD(a){return 5===a[2]?12:-6}function
cO(a){return[0,0,u(a)]}function
cP(a,b){var
c=S(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=u(g);cJ(a[2],0,f,0,c);a[2]=f}return}function
aB(a,b){cP(a,1);E(a[2],a[1],b);a[1]=a[1]+1|0;return}function
y(a,b){var
c=o(b);cP(a,c);$(b,0,a[2],a[1],c);a[1]=a[1]+c|0;return}function
cQ(a){return cI(a[2],0,a[1])}function
cR(a){if(typeof
a==="number")switch(a){case
0:return eV;case
1:return eW;case
2:return eX;case
3:return eY;case
4:return eZ;case
5:return e0;default:return e1}switch(a[0]){case
0:return a[1];case
1:return a[1];default:return"@"+cK(1,a[1])}}function
bE(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];y(a,e2);c=d;break;case
1:var
e=c[1];y(a,e3);c=e;break;case
2:var
f=c[1];y(a,e4);c=f;break;case
3:var
g=c[1];y(a,e5);c=g;break;case
4:var
h=c[1];y(a,e6);c=h;break;case
5:var
i=c[1];y(a,e7);c=i;break;case
6:var
j=c[1];y(a,e8);c=j;break;case
7:var
k=c[1];y(a,e9);c=k;break;case
8:var
l=c[2],m=c[1];y(a,e_);bE(a,m);y(a,e$);c=l;break;case
9:var
n=c[3],o=c[1];y(a,fa);bE(a,o);y(a,fb);c=n;break;case
10:var
p=c[1];y(a,fc);c=p;break;case
11:var
q=c[1];y(a,fd);c=q;break;case
12:var
r=c[1];y(a,fe);c=r;break;case
13:var
s=c[1];y(a,ff);c=s;break;default:var
t=c[1];y(a,fg);c=t}}}function
s(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,s(a[1])];case
1:return[1,s(a[1])];case
2:return[2,s(a[1])];case
3:return[3,s(a[1])];case
4:return[4,s(a[1])];case
5:return[5,s(a[1])];case
6:return[6,s(a[1])];case
7:return[7,s(a[1])];case
8:var
b=a[1];return[8,b,s(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,s(a[3])];case
10:return[10,s(a[1])];case
11:return[11,s(a[1])];case
12:return[12,s(a[1])];case
13:return[13,s(a[1])];default:return[14,s(a[1])]}}function
z(a){if(typeof
a==="number")return[0,function(a){return},function(a){return},function(a){return},function(a){return}];switch(a[0]){case
0:var
b=z(a[1]),r=b[2],u=b[1];return[0,function(a){u(0);return},function(a){r(0);return},b[3],b[4]];case
1:var
c=z(a[1]),v=c[2],w=c[1];return[0,function(a){w(0);return},function(a){v(0);return},c[3],c[4]];case
2:var
d=z(a[1]),x=d[2],y=d[1];return[0,function(a){y(0);return},function(a){x(0);return},d[3],d[4]];case
3:var
e=z(a[1]),A=e[2],B=e[1];return[0,function(a){B(0);return},function(a){A(0);return},e[3],e[4]];case
4:var
f=z(a[1]),C=f[2],D=f[1];return[0,function(a){D(0);return},function(a){C(0);return},f[3],f[4]];case
5:var
g=z(a[1]),E=g[2],F=g[1];return[0,function(a){F(0);return},function(a){E(0);return},g[3],g[4]];case
6:var
h=z(a[1]),G=h[2],H=h[1];return[0,function(a){H(0);return},function(a){G(0);return},h[3],h[4]];case
7:var
i=z(a[1]),I=i[2],J=i[1];return[0,function(a){J(0);return},function(a){I(0);return},i[3],i[4]];case
8:var
j=z(a[2]),K=j[2],L=j[1];return[0,function(a){L(0);return},function(a){K(0);return},j[3],j[4]];case
9:var
M=a[2],N=a[1],k=z(a[3]),O=k[4],P=k[3],Q=k[2],R=k[1],l=z(t(s(N),M)),S=l[4],T=l[3],U=l[2],V=l[1];return[0,function(a){R(0);V(0);return},function(a){U(0);Q(0);return},function(a){P(0);T(0);return},function(a){S(0);O(0);return}];case
10:var
m=z(a[1]),W=m[2],X=m[1];return[0,function(a){X(0);return},function(a){W(0);return},m[3],m[4]];case
11:var
n=z(a[1]),Y=n[2],Z=n[1];return[0,function(a){Z(0);return},function(a){Y(0);return},n[3],n[4]];case
12:var
o=z(a[1]),_=o[2],$=o[1];return[0,function(a){$(0);return},function(a){_(0);return},o[3],o[4]];case
13:var
p=z(a[1]),aa=p[4],ab=p[3],ac=p[2],ad=p[1];return[0,function(a){ad(0);return},function(a){ac(0);return},function(a){ab(0);return},function(a){aa(0);return}];default:var
q=z(a[1]),ae=q[4],af=q[3],ag=q[2],ah=q[1];return[0,function(a){ah(0);return},function(a){ag(0);return},function(a){af(0);return},function(a){ae(0);return}]}}function
t(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,t(d,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,t(e,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,t(f,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
3:var
g=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,t(g,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
4:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,t(i,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
5:var
j=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,t(j,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
6:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,t(k,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
7:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,t(l,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
8:var
m=a[2],n=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
o=b[1],p=t(m,b[2]);return[8,t(n,o),p];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,q,fq],1);case
9:var
r=a[3],u=a[2],v=a[1];if(typeof
b!=="number")switch(b[0]){case
8:break f;case
9:var
w=b[3],x=b[2],y=b[1],c=z(t(s(u),y)),A=c[4];c[2].call(null,0);A(0);return[9,v,x,t(r,w)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,q,fr],1);case
10:var
B=a[1];if(typeof
b!=="number"&&10===b[0])return[10,t(B,b[1])];throw h([0,q,fs],1);case
11:var
C=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:return[11,t(C,b[1])]}throw h([0,q,ft],1);case
12:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:return[12,t(D,b[1])]}throw h([0,q,fu],1);case
13:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:return[13,t(E,b[1])]}throw h([0,q,fv],1);default:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:return[14,t(F,b[1])]}throw h([0,q,fw],1)}throw h([0,q,fp],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw h([0,q,fh],1)}}throw h([0,q,fj],1)}throw h([0,q,fi],1)}throw h([0,q,fo],1)}throw h([0,q,fn],1)}throw h([0,q,fm],1)}throw h([0,q,fl],1)}throw h([0,q,fk],1)}var
v=[c,"CamlinternalFormat.Type_mismatch",bo(0)];function
eB(a){return a?eC:eD}var
eH="\\\\",eI="\\'",eJ="\\b",eK="\\t",eL="\\n",eM="\\r",fy=bV,fz="%+d",fA="% d",fB=dA,fC="%+i",fD="% i",fE="%x",fF="%#x",fG="%X",fH="%#X",fI="%o",fJ="%#o",fK=d7,fL="%Ld",fM="%+Ld",fN="% Ld",fO=du,fP="%+Li",fQ="% Li",fR="%Lx",fS="%#Lx",fT="%LX",fU="%#LX",fV="%Lo",fW="%#Lo",fX="%Lu",fY="%ld",fZ="%+ld",f0="% ld",f1=dn,f2="%+li",f3="% li",f4="%lx",f5="%#lx",f6="%lX",f7="%#lX",f8="%lo",f9="%#lo",f_="%lu",f$="%nd",ga="%+nd",gb="% nd",gc=d6,gd="%+ni",ge="% ni",gf="%nx",gg="%#nx",gh="%nX",gi="%#nX",gj="%no",gk="%#no",gl="%nu",gm=[0,de],gr="neg_infinity",gs=dV,gt=b2,gv=[0,a,1558,4],gw="Printf: bad conversion %[",gx=[0,a,1626,39],gy=[0,a,1649,31],gz=[0,a,1650,31],gA="Printf: bad conversion %_",gB=dL,gC=dC,gD=dL,gE=dC;function
a7(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw h(v,1)}function
aS(a,b,c){var
d=a7(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw h(v,1)}function
l(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
w=l(a[1],b[1]);return[0,[0,w[1]],w[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
x=l(a[1],b[1]);return[0,[1,x[1]],x[2]]}break;case
2:var
ag=a[2],y=a7(a[1],b),e=y[2],ah=y[1];if(typeof
e!=="number"&&1===e[0]){var
z=l(ag,e[1]);return[0,[2,ah,z[1]],z[2]]}throw h(v,1);case
3:var
ai=a[2],A=a7(a[1],b),f=A[2],aj=A[1];if(typeof
f!=="number"&&1===f[0]){var
B=l(ai,f[1]);return[0,[3,aj,B[1]],B[2]]}throw h(v,1);case
4:var
ak=a[4],al=a[1],g=aS(a[2],a[3],b),i=g[3],am=g[1];if(typeof
i!=="number"&&2===i[0]){var
an=g[2],C=l(ak,i[1]);return[0,[4,al,am,an,C[1]],C[2]]}throw h(v,1);case
5:var
ao=a[4],ap=a[1],j=aS(a[2],a[3],b),k=j[3],aq=j[1];if(typeof
k!=="number"&&3===k[0]){var
ar=j[2],E=l(ao,k[1]);return[0,[5,ap,aq,ar,E[1]],E[2]]}throw h(v,1);case
6:var
as=a[4],at=a[1],m=aS(a[2],a[3],b),n=m[3],au=m[1];if(typeof
n!=="number"&&4===n[0]){var
av=m[2],F=l(as,n[1]);return[0,[6,at,au,av,F[1]],F[2]]}throw h(v,1);case
7:var
aw=a[4],ax=a[1],o=aS(a[2],a[3],b),q=o[3],ay=o[1];if(typeof
q!=="number"&&5===q[0]){var
az=o[2],H=l(aw,q[1]);return[0,[7,ax,ay,az,H[1]],H[2]]}throw h(v,1);case
8:var
aA=a[4],aB=a[1],r=aS(a[2],a[3],b),s=r[3],aC=r[1];if(typeof
s!=="number"&&6===s[0]){var
aD=r[2],I=l(aA,s[1]);return[0,[8,aB,aC,aD,I[1]],I[2]]}throw h(v,1);case
9:var
aE=a[2],J=a7(a[1],b),t=J[2],aF=J[1];if(typeof
t!=="number"&&7===t[0]){var
K=l(aE,t[1]);return[0,[9,aF,K[1]],K[2]]}throw h(v,1);case
10:var
L=l(a[1],b);return[0,[10,L[1]],L[2]];case
11:var
aG=a[1],M=l(a[2],b);return[0,[11,aG,M[1]],M[2]];case
12:var
aH=a[1],N=l(a[2],b);return[0,[12,aH,N[1]],N[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
O=b[1],aI=b[2],aJ=a[3],aK=a[1];if(a3([0,a[2]],[0,O]))throw h(v,1);var
P=l(aJ,aI);return[0,[13,aK,O,P[1]],P[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
Q=b[1],aL=b[3],aM=a[3],aN=a[2],aO=a[1],aP=[0,p(Q)];if(a3([0,p(aN)],aP))throw h(v,1);var
R=l(aM,p(aL));return[0,[14,aO,Q,R[1]],R[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
S=l(a[1],b[1]);return[0,[15,S[1]],S[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
T=l(a[1],b[1]);return[0,[16,T[1]],T[2]]}break;case
17:var
aQ=a[1],U=l(a[2],b);return[0,[17,aQ,U[1]],U[2]];case
18:var
V=a[2],u=a[1];if(0===u[0]){var
Z=u[1],aV=Z[2],_=l(Z[1],b),aW=_[1],$=l(V,_[2]);return[0,[18,[0,[0,aW,aV]],$[1]],$[2]]}var
aa=u[1],aX=aa[2],ab=l(aa[1],b),aY=ab[1],ac=l(V,ab[2]);return[0,[18,[1,[0,aY,aX]],ac[1]],ac[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
W=l(a[1],b[1]);return[0,[19,W[1]],W[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aR=a[2],aT=a[1],X=l(a[3],b[1]);return[0,[20,aT,aR,X[1]],X[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aU=a[1],Y=l(a[2],b[1]);return[0,[21,aU,Y[1]],Y[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
0:return G(c,d,b);case
1:return G(c,d,b);case
2:return G(c,d,b);case
3:return G(c,d,b);case
4:return G(c,d,b);case
5:return G(c,d,b);case
6:return G(c,d,b);case
7:return G(c,d,b);case
8:return G([8,c[1],c[2]],d,b);case
9:var
aZ=c[1],ae=D(c[2],d,b),af=ae[2];return[0,[23,[9,aZ,ae[1]],af[1]],af[2]];case
10:return G(c,d,b);default:return G(c,d,b)}switch(c){case
0:return G(c,d,b);case
1:return G(c,d,b);case
2:if(typeof
b!=="number"&&14===b[0]){var
ad=l(d,b[1]);return[0,[23,2,ad[1]],ad[2]]}throw h(v,1);default:return G(c,d,b)}}throw h(v,1)}function
G(a,b,c){var
d=l(b,c);return[0,[23,a,d[1]],d[2]]}function
D(a,b,c){if(typeof
a==="number")return[0,0,l(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=D(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
g=D(a[1],b,c[1]);return[0,[1,g[1]],g[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=D(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
j=D(a[1],b,c[1]);return[0,[3,j[1]],j[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
k=D(a[1],b,c[1]);return[0,[4,k[1]],k[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
m=D(a[1],b,c[1]);return[0,[5,m[1]],m[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
n=D(a[1],b,c[1]);return[0,[6,n[1]],n[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
o=D(a[1],b,c[1]);return[0,[7,o[1]],o[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
q=c[1],C=c[2],E=a[2];if(a3([0,a[1]],[0,q]))throw h(v,1);var
r=D(E,b,C);return[0,[8,q,r[1]],r[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],F=c[3],G=a[3],H=a[2],I=a[1],J=[0,p(e)];if(a3([0,p(I)],J))throw h(v,1);var
K=[0,p(d)];if(a3([0,p(H)],K))throw h(v,1);var
u=z(t(s(e),d)),L=u[4];u[2].call(null,0);L(0);var
w=D(p(G),b,F),M=w[2];return[0,[9,e,d,s(w[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
x=D(a[1],b,c[1]);return[0,[10,x[1]],x[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
y=D(a[1],b,c[1]);return[0,[11,y[1]],y[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
A=D(a[1],b,c[1]);return[0,[13,A[1]],A[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=D(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw h(v,1)}function
H(a,b,c){var
d=o(c),g=0<=b?a:0,f=a6(b);if(f<=d)return c;var
h=2===g?48:32,e=av(f,h);switch(g){case
0:$(c,0,e,0,d);break;case
1:$(c,0,e,f-d|0,d);break;default:a:if(0<d){if(43!==J(c,0)&&45!==J(c,0)&&32!==J(c,0))break a;E(e,0,J(c,0));$(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&48===J(c,0)){if(ds!==J(c,1)&&88!==J(c,1))break a;E(e,1,J(c,1));$(c,2,e,(f-d|0)+2|0,d-2|0);break}$(c,0,e,f-d|0,d)}return F(e)}function
aC(a,b){var
d=a6(a),c=o(b),e=J(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:c:if(c<(d+2|0)&&1<c){if(ds!==J(b,1)&&88!==J(b,1))break c;var
g=av(d+2|0,48);E(g,1,J(b,1));$(b,2,g,(d-c|0)+4|0,c-2|0);return F(g)}break b;case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=av(d+1|0,48);E(f,0,e);$(b,1,f,(d-c|0)+2|0,c-1|0);return F(f)}if(71<=e){if(5<e+dH>>>0)break a}else if(65>e)break a}if(c<d){var
h=av(d,48);$(b,0,h,d-c|0,c);return F(h)}}return b}function
fx(a){a:{b:c:{var
i=0,B=o(a);for(;;){if(B<=i){var
m=a;break a}var
l=aK(a,i)+dW|0;if(59<l>>>0){if(33<l-61>>>0)break c}else if(2===l)break;i=i+1|0}break b}var
e=ap(a),b=[0,0],q=S(e)-1|0,x=0;if(q>=0){var
h=x;for(;;){var
f=cf(e,h);b:{c:{d:{if(32<=f){var
j=f-34|0;if(58<j>>>0){if(93<=j)break d}else if(56<j-1>>>0)break c;var
k=1;break b}if(11<=f){if(13===f)break c}else if(8<=f)break c}var
k=4;break b}var
k=2}b[1]=b[1]+k|0;var
A=h+1|0;if(q===h)break;h=A}}if(b[1]===S(e)){var
n=S(e),p=u(n);af(e,0,p,0,n);var
t=p}else{var
c=u(b[1]);b[1]=0;var
s=S(e)-1|0,y=0;if(s>=0){var
g=y;for(;;){var
d=cf(e,g);b:{c:{d:{if(35<=d){if(92!==d){if(b7<=d)break d;break c}}else{if(32>d){if(14<=d)break d;switch(d){case
8:r(c,b[1],92);b[1]++;r(c,b[1],98);break b;case
9:r(c,b[1],92);b[1]++;r(c,b[1],116);break b;case
10:r(c,b[1],92);b[1]++;r(c,b[1],110);break b;case
13:r(c,b[1],92);b[1]++;r(c,b[1],114);break b;default:break d}}if(34>d)break c}r(c,b[1],92);b[1]++;r(c,b[1],d);break b}r(c,b[1],92);b[1]++;r(c,b[1],48+(d/dJ|0)|0);b[1]++;r(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;r(c,b[1],48+(d%10|0)|0);break b}r(c,b[1],d)}b[1]++;var
z=g+1|0;if(s===g)break;g=z}}var
t=c}var
m=F(t)}var
v=o(m),w=av(v+2|0,34);aZ(m,0,w,1,v);return F(w)}function
cS(a,b){var
g=a6(b),f=gm[1];switch(a[2]){case
0:var
c=102;break;case
1:var
c=101;break;case
2:var
c=69;break;case
3:var
c=de;break;case
4:var
c=71;break;case
5:var
c=f;break;case
6:var
c=104;break;case
7:var
c=72;break;default:var
c=70}var
d=cO(16);aB(d,37);switch(a[1]){case
0:break;case
1:aB(d,43);break;default:aB(d,32)}if(8<=a[2])aB(d,35);aB(d,46);y(d,e+g);aB(d,c);return cQ(d)}function
a8(a,b){if(13>a)return b;var
h=[0,0],i=o(b)-1|0,n=0;if(i>=0){var
d=n;for(;;){if(9>=aK(b,d)+dk>>>0)h[1]++;var
r=d+1|0;if(i===d)break;d=r}}var
j=h[1],k=u(o(b)+((j-1|0)/3|0)|0),l=[0,0];function
e(a){E(k,l[1],a);l[1]++;return}var
f=[0,((j-1|0)%3|0)+1|0],m=o(b)-1|0,p=0;if(m>=0){var
c=p;for(;;){var
g=aK(b,c);if(9<g+dk>>>0)e(g);else{if(0===f[1]){e(95);f[1]=3}f[1]--;e(g)}var
q=c+1|0;if(m===c)break;c=q}}return F(k)}function
gn(a,b){switch(a){case
1:var
c=fz;break;case
2:var
c=fA;break;case
4:var
c=fC;break;case
5:var
c=fD;break;case
6:var
c=fE;break;case
7:var
c=fF;break;case
8:var
c=fG;break;case
9:var
c=fH;break;case
10:var
c=fI;break;case
11:var
c=fJ;break;case
0:case
13:var
c=fy;break;case
3:case
14:var
c=fB;break;default:var
c=fK}return a8(a,bn(c,b))}function
go(a,b){switch(a){case
1:var
c=fZ;break;case
2:var
c=f0;break;case
4:var
c=f2;break;case
5:var
c=f3;break;case
6:var
c=f4;break;case
7:var
c=f5;break;case
8:var
c=f6;break;case
9:var
c=f7;break;case
10:var
c=f8;break;case
11:var
c=f9;break;case
0:case
13:var
c=fY;break;case
3:case
14:var
c=f1;break;default:var
c=f_}return a8(a,bn(c,b))}function
gp(a,b){switch(a){case
1:var
c=ga;break;case
2:var
c=gb;break;case
4:var
c=gd;break;case
5:var
c=ge;break;case
6:var
c=gf;break;case
7:var
c=gg;break;case
8:var
c=gh;break;case
9:var
c=gi;break;case
10:var
c=gj;break;case
11:var
c=gk;break;case
0:case
13:var
c=f$;break;case
3:case
14:var
c=gc;break;default:var
c=gl}return a8(a,bn(c,b))}function
gq(a,b){switch(a){case
1:var
c=fM;break;case
2:var
c=fN;break;case
4:var
c=fP;break;case
5:var
c=fQ;break;case
6:var
c=fR;break;case
7:var
c=fS;break;case
8:var
c=fT;break;case
9:var
c=fU;break;case
10:var
c=fV;break;case
11:var
c=fW;break;case
0:case
13:var
c=fL;break;case
3:case
14:var
c=fO;break;default:var
c=fX}return a8(a,hN(c,b))}function
aa(d,b,c){function
j(a){switch(d[1]){case
0:var
e=45;break;case
1:var
e=43;break;default:var
e=32}return hJ(c,b,e)}function
q(a){var
b=hB(c);return 3===b?c<0.?gr:gs:4<=b?gt:a}switch(d[2]){case
5:var
f=ci(cS(d,b),c),e=0,w=o(f);for(;;){if(e===w)var
p=0;else{var
k=J(f,e)-46|0;a:{if(23<k>>>0){if(55===k)break a}else if(21<k-1>>>0)break a;e=e+1|0;continue}var
p=1}var
x=p?f:f+an;return q(x)}case
6:return j(0);case
7:var
i=ap(j(0)),g=S(i);if(0===g)var
n=i;else{var
l=u(g),m=g-1|0,s=0;if(m>=0){var
a=s;for(;;){var
h=cf(i,a),t=25<h+dH>>>0?h:h+dW|0;r(l,a,t);var
v=a+1|0;if(m===a)break;a=v}}var
n=l}return F(n);case
8:return q(j(0));default:return ci(cS(d,b),c)}}function
aU(a,b,c,d){var
f=b,e=c,g=d;for(;;){if(typeof
g==="number")return n(f,e);switch(g[0]){case
0:var
O=g[1];return function(a){return i(f,[5,e,a],O)};case
1:var
P=g[1];return function(a){a:{b:{if(40<=a){if(92===a){var
b=eH;break a}if(b7>a)break b}else{if(32<=a){if(39>a)break b;var
b=eI;break a}if(14>a)switch(a){case
8:var
b=eJ;break a;case
9:var
b=eK;break a;case
10:var
b=eL;break a;case
13:var
b=eM;break a}}var
c=u(4);r(c,0,92);r(c,1,48+(a/dJ|0)|0);r(c,2,48+((a/10|0)%10|0)|0);r(c,3,48+(a%10|0)|0);var
b=F(c);break a}var
d=u(1);r(d,0,a);var
b=F(d)}var
g=o(b),h=av(g+2|0,39);aZ(b,0,h,1,g);return i(f,[4,e,F(h)],P)};case
2:return bF(f,e,g[2],g[1],function(a){return a});case
3:return bF(f,e,g[2],g[1],fx);case
4:return a9(f,e,g[4],g[2],g[3],gn,g[1]);case
5:return a9(f,e,g[4],g[2],g[3],go,g[1]);case
6:return a9(f,e,g[4],g[2],g[3],gp,g[1]);case
7:return a9(f,e,g[4],g[2],g[3],gq,g[1]);case
8:var
w=g[4],y=g[3],z=g[2],t=g[1];if(typeof
z==="number"){if(typeof
y==="number")return y?function(a,b){return i(f,[4,e,aa(t,a,b)],w)}:function(a){return i(f,[4,e,aa(t,bD(t),a)],w)};var
_=y[1];return function(a){return i(f,[4,e,aa(t,_,a)],w)}}if(0===z[0]){var
C=z[2],D=z[1];if(typeof
y==="number")return y?function(a,b){return i(f,[4,e,H(D,C,aa(t,a,b))],w)}:function(a){return i(f,[4,e,H(D,C,aa(t,bD(t),a))],w)};var
$=y[1];return function(a){return i(f,[4,e,H(D,C,aa(t,$,a))],w)}}var
E=z[1];if(typeof
y==="number")return y?function(a,b,c){return i(f,[4,e,H(E,a,aa(t,b,c))],w)}:function(a,b){return i(f,[4,e,H(E,a,aa(t,bD(t),b))],w)};var
ab=y[1];return function(a,b){return i(f,[4,e,H(E,a,aa(t,ab,b))],w)};case
9:return bF(f,e,g[2],g[1],eB);case
10:e=[7,e];g=g[1];break;case
11:e=[2,e,g[1]];g=g[2];break;case
12:e=[3,e,g[1]];g=g[2];break;case
13:var
Q=g[3],R=g[2],G=cO(16);bE(G,R);var
N=cQ(G);return function(a){return i(f,[4,e,N],Q)};case
14:var
S=g[3],T=g[2];return function(a){var
c=a[1],b=l(c,p(s(T)));if(typeof
b[2]==="number")return i(f,e,m(b[1],S));throw h(v,1)};case
15:var
U=g[1];return function(c,b){return i(f,[6,e,function(a){return M(c,a,b)}],U)};case
16:var
V=g[1];return function(a){return i(f,[6,e,a],V)};case
17:e=[0,e,g[1]];g=g[2];break;case
18:var
B=g[1];if(0===B[0]){let
b=e,c=f,d=g[2];f=function(a){return i(c,[1,b,[0,a]],d)};e=0;g=B[1][1]}else{let
b=e,c=f,d=g[2];f=function(a){return i(c,[1,b,[1,a]],d)};e=0;g=B[1][1]}break;case
19:throw h([0,q,gv],1);case
20:var
W=g[3],X=[8,e,gw];return function(a){return i(f,X,W)};case
21:var
Y=g[2];return function(a){return i(f,[4,e,bn(d7,a)],Y)};case
22:var
Z=g[1];return function(a){return i(f,[5,e,a],Z)};case
23:var
j=g[2],A=g[1];if(typeof
A==="number")switch(A){case
0:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
1:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
2:throw h([0,q,gx],1);default:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j])}switch(A[0]){case
0:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
1:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
2:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
3:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
4:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
5:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
6:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
7:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
8:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);case
9:var
L=A[2];return a<50?bR(a+1|0,f,e,L,j):x(bR,[0,f,e,L,j]);case
10:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j]);default:return a<50?k(a+1|0,f,e,j):x(k,[0,f,e,j])}default:var
I=g[3],J=g[1],K=n(g[2],0);return a<50?bQ(a+1|0,f,e,I,J,K):x(bQ,[0,f,e,I,J,K])}}}function
i(a,b,c){return cw(aU(0,a,b,c))}function
bR(a,f,c,d,e){if(typeof
d==="number")return a<50?k(a+1|0,f,c,e):x(k,[0,f,c,e]);switch(d[0]){case
0:var
b=d[1];return function(a){return K(f,c,b,e)};case
1:var
g=d[1];return function(a){return K(f,c,g,e)};case
2:var
i=d[1];return function(a){return K(f,c,i,e)};case
3:var
j=d[1];return function(a){return K(f,c,j,e)};case
4:var
l=d[1];return function(a){return K(f,c,l,e)};case
5:var
m=d[1];return function(a){return K(f,c,m,e)};case
6:var
n=d[1];return function(a){return K(f,c,n,e)};case
7:var
o=d[1];return function(a){return K(f,c,o,e)};case
8:var
p=d[2];return function(a){return K(f,c,p,e)};case
9:var
r=d[3],u=d[2],v=t(s(d[1]),u);return function(a){return K(f,c,A(v,r),e)};case
10:var
w=d[1];return function(a,b){return K(f,c,w,e)};case
11:var
y=d[1];return function(a){return K(f,c,y,e)};case
12:var
z=d[1];return function(a){return K(f,c,z,e)};case
13:throw h([0,q,gy],1);default:throw h([0,q,gz],1)}}function
K(a,b,c,d){return cw(bR(0,a,b,c,d))}function
k(a,b,c,d){var
e=[8,c,gA];return a<50?aU(a+1|0,b,e,d):x(aU,[0,b,e,d])}function
bF(g,f,c,d,e){if(typeof
d==="number")return function(a){return i(g,[4,f,n(e,a)],c)};if(0===d[0]){var
b=d[2],h=d[1];return function(a){return i(g,[4,f,H(h,b,n(e,a))],c)}}var
j=d[1];return function(a,b){return i(g,[4,f,H(j,a,n(e,b))],c)}}function
a9(k,j,h,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b){return i(k,[4,j,aC(a,M(f,g,b))],h)}:function(a){return i(k,[4,j,M(f,g,a)],h)};var
b=e[1];return function(a){return i(k,[4,j,aC(b,M(f,g,a))],h)}}if(0===d[0]){var
c=d[2],l=d[1];if(typeof
e==="number")return e?function(a,b){return i(k,[4,j,H(l,c,aC(a,M(f,g,b)))],h)}:function(a){return i(k,[4,j,H(l,c,M(f,g,a))],h)};var
n=e[1];return function(a){return i(k,[4,j,H(l,c,aC(n,M(f,g,a)))],h)}}var
m=d[1];if(typeof
e==="number")return e?function(a,b,c){return i(k,[4,j,H(m,a,aC(b,M(f,g,c)))],h)}:function(a,b){return i(k,[4,j,H(m,a,M(f,g,b))],h)};var
o=e[1];return function(a,b){return i(k,[4,j,H(m,a,aC(o,M(f,g,b)))],h)}}function
bQ(a,b,c,d,e,f){if(e){var
h=e[1];return function(a){return gu(b,c,d,h,n(f,a))}}var
g=[4,c,f];return a<50?aU(a+1|0,b,g,d):x(aU,[0,b,g,d])}function
gu(a,b,c,d,e){return cw(bQ(0,a,b,c,d,e))}function
ab(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
f=c[1],g=cR(c[2]);ab(a,f);return aN(a,g);case
1:var
d=c[2],e=c[1];if(0===d[0]){var
h=d[1];ab(a,e);aN(a,gB);c=h}else{var
i=d[1];ab(a,e);aN(a,gC);c=i}break;case
6:var
l=c[2];ab(a,c[1]);return n(l,a);case
7:ab(a,c[1]);Z(a);return;case
8:var
m=c[2];ab(a,c[1]);return aj(m);case
2:case
4:var
j=c[2];ab(a,c[1]);return aN(a,j);default:var
k=c[2];ab(a,c[1]);er(a,k);return}}}function
ak(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
g=c[1],h=cR(c[2]);ak(a,g);return aR(a,h);case
1:var
e=c[2],f=c[1];if(0===e[0]){var
i=e[1];ak(a,f);aR(a,gD);c=i}else{var
j=e[1];ak(a,f);aR(a,gE);c=j}break;case
6:var
m=c[2];ak(a,c[1]);return aR(a,n(m,0));case
7:c=c[1];break;case
8:var
o=c[2];ak(a,c[1]);return aj(o);case
2:case
4:var
k=c[2];ak(a,c[1]);return aR(a,k);default:var
l=c[2];ak(a,c[1]);var
d=a[2];if(a[3]<=d)bC(a,1);r(a[1],d,l);a[2]=d+1|0;return}}}function
a_(c,b){return i(function(a){ab(c,a);return 0},0,b[1])}function
T(a){return i(function(a){var
b=cN(64);ak(b,a);return cI(b[1],0,b[2])},0,a[1])}var
bP=[0,0],gF=[0,[3,0,0],"%S"],gG=dD,gH=[0,[4,0,0,0,0],bV],gI=e,gJ=[0,[11,dq,[2,0,[2,0,0]]],", %s%s"],gK=[0,[12,40,[2,0,[2,0,[12,41,0]]]],"(%s%s)"],gL=e,gM=e,gN=[0,[12,40,[2,0,[12,41,0]]],"(%s)"],gO="Out of memory",gP="Stack overflow",gQ="Pattern matching failed",gR="Assertion failed",gS="Undefined recursive module",gT="Raised at",gU="Re-raised at",gV="Raised by primitive operation at",gW="Called from",gX=" (inlined)",gY=[0,[2,0,[12,32,[2,0,[11,' in file "',[2,0,[12,34,[2,0,[11,", line ",[4,0,0,0,[11,d1,hu]]]]]]]]]],'%s %s in file "%s"%s, line %d, characters %d-%d'],gZ=e,g0=[0,[2,0,[11," unknown location",0]],"%s unknown location"],g1=[0,[2,0,[12,10,0]],"%s\n"];function
bH(a,b){var
c=a[1+b];if(!(1-(typeof
c==="number"?1:0)))return n(T(gH),c);if(br(c)===be)return n(T(gF),c);if(br(c)!==253)return gG;var
e=ci("%.12g",c),d=0,g=o(e);for(;;){if(g<=d)return e+an;var
f=J(e,d);a:{if(48<=f){if(58>f)break a}else if(45===f)break a;return e}d=d+1|0}}function
cT(a,b){if(a.length-1<=b)return gI;var
c=cT(a,b+1|0),d=bH(a,b);return M(T(gJ),d,c)}function
bI(a){a:{b:{var
b=bP[1];for(;;){if(!b)break;c:{var
r=b[2],s=b[1];try{var
i=n(s,a)}catch(f){break c}if(i)break b}b=r}var
g=0;break a}var
g=[0,i[1]]}if(g)return g[1];if(a===bz)return gO;if(a===cD)return gP;if(a[1]===cC){var
d=a[2],j=d[3],t=d[2],u=d[1];return bS(T(bG),u,t,j,j+5|0,gQ)}if(a[1]===q){var
e=a[2],k=e[3],v=e[2],w=e[1];return bS(T(bG),w,v,k,k+6|0,gR)}if(a[1]===cF){var
f=a[2],l=f[3],x=f[2],y=f[1];return bS(T(bG),y,x,l,l+6|0,gS)}if(0!==br(a))return a[1];var
h=a.length-1,z=a[1][1];if(2<h>>>0)var
m=cT(a,2),o=bH(a,1),c=M(T(gK),o,m);else
switch(h){case
0:var
c=gL;break;case
1:var
c=gM;break;default:var
p=bH(a,1),c=n(T(gN),p)}return z+c}function
bJ(a,b){var
f=hC(b),h=f.length-2|0,r=0;if(h>=0){var
d=r;for(;;){var
c=ef(f,d)[1+d];let
b=d;var
g=function(a){return a?0===b?gT:gU:0===b?gV:gW};if(0===c[0])var
i=c[5],j=c[4],k=c[3],l=c[6]?gX:gZ,m=c[2],o=c[7],p=g(c[1]),e=[0,hv(T(gY),p,o,m,l,k,j,i)];else if(c[1])var
e=0;else
var
q=g(0),e=[0,n(T(g0),q)];if(e){var
s=e[1];n(a_(a,g1),s)}var
t=d+1|0;if(h===d)break;d=t}}return}function
cU(a){for(;;){var
c=bP[1],b=1-bx(bP,c,[0,a,c]);if(!b)return b}}var
g2=[0,e,"(Cannot print locations:\n bytecode executable program file not found)","(Cannot print locations:\n bytecode executable program file appears to be corrupt)","(Cannot print locations:\n bytecode executable program file has wrong magic number)","(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)"].slice(),g3=[0,[11,b0,[2,0,[12,10,0]]],dg],g4=[0],g5="Fatal error: out of memory in uncaught exception handler",g6=[0,[11,b0,[2,0,[12,10,0]]],dg],g7=[0,[11,"Fatal error in uncaught exception handler: exception ",[2,0,[12,10,0]]],"Fatal error in uncaught exception handler: exception %s\n"];cv(dI,function(a,b){try{try{var
g=b?g4:el(0);try{bA(0)}catch(f){}try{var
f=bI(a);n(a_(L,g3),f);bJ(L,g);var
c=h3(0);if(c<0){var
d=a6(c);cG(ef(g2,d)[1+d])}var
o=Z(L),i=o}catch(f){var
k=a4(f),l=bI(a);n(a_(L,g6),l);bJ(L,g);var
m=bI(k);n(a_(L,g7),m);bJ(L,el(0));var
i=Z(L)}var
j=i}catch(f){var
e=a4(f);if(e!==bz)throw h(e,0);var
j=cG(g5)}return j}catch(f){return 0}});var
cV=0,cW=-1,cX=[c,"Stdlib.Format.String_tag",bo(0)];function
a$(a,b){a[13]=a[13]+b[3]|0;return cM(b,a[28])}var
cY=1000000010,eQ=[c,"Stdlib.Queue.Empty",bo(0)],g9=e,g_=e,g$=e,ha=e,hb=[0,e];function
bK(a,b){return bc(a[17],b,0,o(b))}function
bL(a){return n(a[19],0)}function
cZ(a,b,c){a[9]=a[9]-b|0;bK(a,c);a[11]=0;return}function
ba(a,b){var
c=b!==e?1:0;return c?cZ(a,o(b),b):c}function
al(a,b,c){var
f=b[3],g=b[2];ba(a,b[1]);bL(a);a[11]=1;var
d=(a[6]-c|0)+g|0,e=a[8],h=e<=d?e:d;a[10]=h;a[9]=a[6]-a[10]|0;n(a[21],a[10]);return ba(a,f)}function
aD(a,b){var
c=b[2],d=b[3];ba(a,b[1]);a[9]=a[9]-c|0;n(a[20],c);return ba(a,d)}function
g8(a,b,c){if(typeof
c==="number")switch(c){case
0:var
t=aA(a[3]);if(!t)return;var
u=t[1][1],v=function(a,b){if(!b)return[0,a,0];var
c=b[1],d=b[2];return h1(a,c)?[0,a,b]:[0,c,v(a,d)]};u[1]=v(a[6]-a[9]|0,u[1]);return;case
1:az(a[2]);return;case
2:az(a[3]);return;case
3:var
w=aA(a[2]);return w?al(a,c0,w[1][2]):bL(a);case
4:var
x=a[10]!==(a[6]-a[9]|0)?1:0;if(!x)return x;var
f=a[28],h=f[2];if(h){var
m=h[1];if(h[2]){var
K=h[2];f[1]=f[1]-1|0;f[2]=K;var
i=[0,m]}else{bB(f);var
i=[0,m]}}else
var
i=0;if(!i)return;var
s=i[1],M=s[1];a[12]=a[12]-s[3]|0;a[9]=a[9]+M|0;return;default:var
y=az(a[5]);if(y)return bK(a,n(a[25],y[1]));return}switch(c[0]){case
0:return cZ(a,b,c[1]);case
1:var
d=c[2],g=c[1],z=d[1],N=d[2],A=aA(a[2]);if(!A)return;var
B=A[1],e=B[2];switch(B[1]){case
0:return aD(a,g);case
1:return al(a,d,e);case
2:return al(a,d,e);case
3:return a[9]<(b+o(z)|0)?al(a,d,e):aD(a,g);case
4:return a[11]?aD(a,g):a[9]<(b+o(z)|0)?al(a,d,e):((a[6]-e|0)+N|0)<a[10]?al(a,d,e):aD(a,g);default:return aD(a,g)}case
2:var
k=a[6]-a[9]|0,O=c[2],P=c[1],C=aA(a[3]);if(!C)return;var
D=C[1][1],E=D[1];if(E){var
j=D[1],Q=E[1];for(;;){if(j){var
F=j[1],R=j[2];if(k>F){j=R;continue}var
G=F}else
var
G=Q;var
l=G;break}}else
var
l=k;var
H=l-k|0;return 0<=H?aD(a,[0,g_,H+P|0,g9]):al(a,[0,ha,l+O|0,g$],a[6]);case
3:var
I=c[2],S=c[1];if(a[8]<(a[6]-a[9]|0)){var
p=aA(a[2]);if(p){var
q=p[1],r=q[2],L=q[1];if(a[9]<r&&3>=L-1>>>0)al(a,c0,r)}else
bL(a)}var
T=a[9]-S|0,U=1===I?1:a[9]<b?I:5;return ay([0,U,T],a[2]);case
4:return ay(c[1],a[3]);default:var
J=c[1];bK(a,n(a[24],J));return ay(J,a[5])}}function
c1(a){for(;;){var
f=a[28][2],g=f?[0,f[1]]:0;if(!g)return;var
d=g[1],e=d[1],k=0<=e?1:0,l=d[3],m=d[2],n=a[13]-a[12]|0,i=k||(a[9]<=n?1:0);if(!i)return i;var
b=a[28],c=b[2];if(!c)throw h(eQ,1);if(c[2]){var
j=c[2];b[1]=b[1]-1|0;b[2]=j}else
bB(b);var
o=0<=e?e:cY;g8(a,o,m);a[12]=l+a[12]|0}}function
bM(a){aQ(a);return ay([0,-1,[0,cW,hb,0]],a)}function
c2(a,b){var
d=aA(a[1]);if(!d)return;var
e=d[1],c=e[2],f=c[1];if(e[1]<a[12])return bM(a[1]);var
g=c[2];if(typeof
g!=="number")switch(g[0]){case
3:if(1-b){c[1]=a[13]+f|0;az(a[1])}return;case
1:case
2:if(b){c[1]=a[13]+f|0;az(a[1])}return}return}function
c3(a,b){var
c=a[4][1];for(;;){if(!c)break;var
h=c[2];if(a[23])a$(a,[0,cV,5,0]);a:if(a[22]){var
g=az(a[4]);if(g){n(a[27],g[1]);break a}}c=h}for(;;){if(1>=a[14])break;if(1<a[14]){if(a[14]<a[15]){a$(a,[0,cV,1,0]);c2(a,1);c2(a,0)}a[14]=a[14]-1|0}}a[13]=cY;c1(a);a[12]=1;a[13]=1;bB(a[28]);bM(a[1]);aQ(a[2]);aQ(a[3]);aQ(a[4]);aQ(a[5]);a[10]=0;a[14]=0;a[9]=a[6];a[14]=a[14]+1|0;var
i=3,j=0;if(a[14]<a[15]){var
e=[0,-a[13]|0,[3,j,i],0];a$(a,e);ay([0,a[13],e],a[1])}else if(a[14]===a[15]){var
f=a[16],d=o(f);a$(a,[0,d,[0,f],d]);c1(a)}return n(a[18],0)}var
c4=cK(80,32),eA=2147483647,eF="output_substring",hc=dP,he=e,hg=e,hj=[3,0,3],hk=an;function
c5(a,b){var
c=b;for(;;){var
d=0<c?1:0;if(!d)return d;if(80>=c)return bc(a[17],c4,0,c);bc(a[17],c4,0,80);c=c-80|0}}function
hd(a){return a[1]===cX?"<"+a[2]+dG:he}function
hf(a){return a[1]===cX?"<\/"+a[2]+dG:hg}function
hh(a){return 0}function
hi(a){return 0}function
c6(a,b,c,d,e){var
g=[0,0,0,0],h=[0,cW,hj,0];cM(h,g);var
f=aP(0);bM(f);ay([0,1,h],f);var
i=78,j=aP(0),k=aP(0),l=aP(0);return[0,f,aP(0),l,k,j,i,10,68,i,0,1,1,1,1,eA,hk,a,b,c,d,e,0,0,hd,hf,hh,hi,g]}function
c7(a,b){var
c=c6(a,b,function(a){return 0},function(a){return 0},function(a){return 0});c[19]=function(a){return bc(c[17],hc,0,1)};c[20]=function(a){return c5(c,a)};c[21]=function(a){return c5(c,a)};return c}function
c8(d){return c7(function(a,b,c){if(0<=b&&0<=c&&(o(a)-c|0)>=b)return cr(d,a,b,c);return aj(eF)},function(a){return Z(d)})}var
aE=cN(b3),hl=c8(eE),eU="Buffer.add_substring/add_subbytes",hm=c8(L);c7(function(a,b,c){var
d=b<0?1:0;if(d)var
e=d;else
var
g=c<0?1:0,e=g||((o(a)-c|0)<b?1:0);if(e)aj(eU);var
f=aE[2]+c|0;if(aE[3]<f)bC(aE,c);aZ(a,b,aE[1],aE[2],c);aE[2]=f;return 0},function(a){return 0});var
eG="Char.chr",ho="Jsoo_runtime.Error.Exn",hs=W,hr=dP,ht="todo";for(;;){var
db=bw[1];let
b=db,c=[0,1];if(!(1-bx(bw,db,function(a){if(bx(c,1,0)){c3(hl,0);c3(hm,0)}return n(b,0)})))break}var
c9=[c,ho,bo(0)],bN=[0,c9,[0]],hn=br(bN)===c?bN:bN[1];cv(bT,hn);(function(a){throw a});var
P=f,c_=null,aT=true;P.String;P.RegExp;P.Object;P.Date;P.Math;P.Error;P.JSON;var
hp=P.Array;cU(function(a){return a[1]===c9?[0,_(a[2].toString())]:0});cU(function(a){return a
instanceof
hp?0:[0,_(a.toString())]});var
hq=P.document;1-(P.HTMLElement===undefined?1:0);P.onload=h0(function(a){if(1-(a==c_?1:0)){if(1-(aT|0))a.preventDefault();return aT}var
b=event;if(1-(aT|0))b.returnValue=aT;return aT});function
am(a){var
c=a&15,d=10<=c?55:48,b=c+d|0;if(0<=b&&aF>=b)return b;return aj(eG)}var
U=u(9);E(U,0,35);E(U,1,am(15));E(U,2,am(aF));E(U,3,am(15));E(U,4,am(aF));E(U,5,am(15));E(U,6,am(aF));E(U,7,am(159));E(U,8,am(2555));F(U);try{var
bb=hq.getElementById(d8);if(bb==c_)throw h(aM,1);var
bO=function(a,b,c){var
g=cL(a,b,c);a:{try{var
d=0,k=o(g);for(;;){if(k<=d)throw h(aM,1);if(aK(g,d)===0)break;d=d+1|0}}catch(f){var
i=a4(f);if(i!==aM)throw h(i,0);var
j=g;break a}bb.innerHTML=e;var
f=d+1|0,j=cL(g,f,o(g)-f|0)}return bb.innerHTML=bb.innerHTML.concat(cq(j))},da=function(a){var
c=a-1|0,d=0;if(c>=0){var
b=d;for(;;){bO(hs,0,1);var
e=b+1|0;if(c===b)break;b=e}}return 0};c6(bO,function(a){return 0},function(a){return bO(hr,0,1)},da,da)}catch(f){var
c$=a4(f);if(c$!==aM)throw h(c$,0);by("No element with id "+d8)}by(ht);bA(0);return}(globalThis));
